<?php

require('../common_head_for_help_page.php');

?>


<div style="height:820px;width:760px;overflow-y:hidden;overflow-x:hidden">
<p style="margin-left:20px"><font  size="3"> <b>How to collect leaf senescence phenotype images?</b><hr  width="740px" align="right"/></font></p>
<p style="margin-left:20px"><font  size="2"> 
In order to determine whether SAGs collected in LSD really affect leaf senescence process, we selected T-DNA insertion lines via <a href='http://signal.salk.edu/' target='_blank'><b>SIGnaL</b></a> and ordered them from <a href='http://abrc.osu.edu/' target='_blank'><b>ABRC</b></a>. If multiple insertions are available in the same gene, the insertion which disrupts the gene function at the largest degree is selected, such as those locating within exons.<br/><br/>
Some RNAi lines were generated by ourselves or obtained from other laboratories for further study if there is no suitable insertion lines available from the Salk collections.<br/><br/>
To conduct the phenotype analysis, we did the following works:<br/><br/>
1. Phenotype information of mutants or transgenic plants were collected as descripted above.<br/>
2. A large scale phenotype analysis was carried on and phenotype images were deposited in the updated database.<br/>
3. We constructed several transgenic plants overexpressing SAGs (WRKY75, WRKY51, WRKY26, bZIP60, EIN2-CEND/ein2-5) to study their regulatory functions in leaf senescence process. More transgenic plants will be available in the near future.<br/><br/>
Currently, LSD stores 108 pieces of phenotype images.<br/>
</font></p>

</div>
   </td>
   </tr>

<?php
require ('../common_footer.php');
?>
</table>




 </body>
</html>



