<?php

require ('dbconnect.php');
require ('code.php');

?>




<html>
  <head>
    <title>Main</title>
    <link rel="stylesheet" type="text/css" href="style.css" />
	 <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	  <script type="text/javascript" src="js/jquery-1.2.6.min.js"></script>
	<script type="text/javascript" src="js/jquery-easing-1.3.pack.js"></script>
	<script type="text/javascript" src="js/jquery-easing-compatibility.1.2.pack.js"></script>
	<script type="text/javascript" src="js/coda-slider.1.1.1.pack.js"></script>
	
	<script type="text/javascript">
	
		var theInt = null;
		var $crosslink, $navthumb;
		var curclicked = 0;
		
		theInterval = function(cur){
			clearInterval(theInt);
			
			if( typeof cur != 'undefined' )
				curclicked = cur;
			
			$crosslink.removeClass("active-thumb");
			$navthumb.eq(curclicked).parent().addClass("active-thumb");
				$(".stripNav ul li a").eq(curclicked).trigger('click');
			
			theInt = setInterval(function(){
				$crosslink.removeClass("active-thumb");
				$navthumb.eq(curclicked).parent().addClass("active-thumb");
				$(".stripNav ul li a").eq(curclicked).trigger('click');
				curclicked++;
				if( 5 == curclicked )
					curclicked = 0;
				
			}, 8000);
		};
		
		/*$(function(){
			
			$("#main-photo-slider").codaSlider();
			
			$navthumb = $(".nav-thumb");
			$crosslink = $(".cross-link");
			
			$navthumb
			.click(function() {
				var $this = $(this);
				theInterval($this.parent().attr('href').slice(1) - 1);
				return false;
			});
			
			theInterval();
		});*/
	</script>	
  </head>
  <body >
  <br/>
  <br/>
  <div  class="al">
	
    	<p  class="info" align="center">Welcome to LSD 2.0: Leaf Senescence Database Update!</p> <hr width="760px" align="left" />
	  	 
	</div>
	
	
<div class="kk" style="margin-left:20px;">

<p class="sltext" style="font-size:14px; line-height: 23px;">Leaf senescence has been recognized as the last phase of plant development, a highly ordered process regulated by senescence associated genes (SAGs). Leaf senescence is induced during plant development or resulted by environmental changes. Premature senescence leads to reduced yield and quality of crops.<br/><br/>To facilitate the systematical research and comparative study of leaf senescence, we constructed a database of leaf senescence (<a href = '/index.php' target = '_blank'><b>LSD 1.0</a></p>, August 2011) to collect SAGs, mutants, phenotypes and literature references. We now update LSD to a new version LSD 2.0 (June, 2013).<br/><br/>LSD 2.0 contains <b>5356</b> genes and <b>322</b> mutants. New features of LSD 2.0 are:<br/></b>
<p class="sltext" style="font-size:12px; line-height: 23px;">
<b>
. 108 images of <i>Arabidopsis thaliana</i> mutants are added<br/>
. Subcellular localization information of <i>Arabidopsis thaliana</i> SAGs mined from literature or generated by <a href = 'http://suba.plantenergy.uwa.edu.au/' target = '_blank'>SUBA3</a> is added<br/>
. Mutant seed information of <i>Arabidopsis thaliana</i> obtained from <a href = 'http://www.arabidopsis.org/' target = '_blank'>TAIR</a> is integrated</br>
. stay-green QTL information is added and linked to the <a href="http://www.gramene.org/qtl/" target="_blank"><b>Gramene QTL Database</b></a><br/>
. Primer sequences of SAGs retrieved from research papers or designed by <a href='http://www.premierbiosoft.com/' target='_blank'><b>Array Designer 4</b></a> are added<br/>
. New options of search engines for primers of SAGs and interactions between miRNAs and SAGs are implemented<br/><br/></b></p>

<!--
<div id="page-wrap">			
	<div class="slider-wrap">
		<div id="main-photo-slider" class="csw">
			<div class="panelContainer">
				<div class="panel" title="Panel 1">
					<div class="wrapper">
						<img src="image/tree3.jpg" alt="temp" />
					</div>
				</div>
				<div class="panel" title="Panel 2">
					<div class="wrapper">
						<img src="image/subcellular_location.jpg" alt="temp" />
					</div>
				</div>		
				<div class="panel" title="Panel 3">
					<div class="wrapper">
						<img src="image/pic5.jpg" alt="temp" />
						<div class="photo-meta-data">
							&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Control&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Darkness treatment<br />
							<span> &nbsp;&nbsp;</span> 				</div>
					</div>
				</div>
				<div class="panel" title="Panel 4">
					<div class="wrapper">
						
						<img src="image/phenotype.jpg" alt="scotch egg" class="floatLeft"/>
						<br><br><br><br>Wild Type<br><br><br><br><br><br><br><br>Early-senescence mutant
					</div>
				</div>
				<div class="panel" title="Panel 5">
					<div class="wrapper">
						<img src="image/pic2.jpg" alt="temp" />
						<div class="photo-meta-data">
							The Number of Genes in Leaf Senescence DataBase<br/>
							<span> &nbsp;&nbsp;</span> 
						</div>
					</div>
				</div>
			</div>
		</div>

		<a href="#1" class="cross-link active-thumb"><img src="image/tree3-thumb.jpg" class="nav-thumb" alt="temp-thumb" /></a>
		<div id="movers-row">
		    <div><a href="#2" class="cross-link"><img src="image/subcellular_location-thumb.jpg" class="nav-thumb" alt="temp-thumb" /></a></div>
			<div><a href="#3" class="cross-link"><img src="image/pic5-5thumb.jpg" class="nav-thumb" alt="temp-thumb" /></a></div>
			<div><a href="#4" class="cross-link"><img src="image/phenotype-thumb.jpg" class="nav-thumb" alt="temp-thumb" /></a></div>
			<div><a href="#5" class="cross-link"><img src="image/pic2-2thumb.jpg" class="nav-thumb" alt="temp-thumb" /></a></div>
		</div>
	</div>
</div>
-->

<div>
	<br/><br/><img src="image/SAGs_species.png" width="460" height="296" /><br/><br/><br/>
	<a target="_blank" href="show_img.php?url=image/IMGP9545-2.jpg"><img border="0" src="image/IMGP9545-2.jpg" width="140" height="95" /></a>
	<a target="_blank" href="show_img.php?url=image/Subcellular_localization.png"><img border="0" src="image/Subcellular_localization.png" width="140" height="95" /></a>
	<a target="_blank" href="show_img.php?url=image/EIN2Cox.png"><img border="0" src="image/EIN2Cox.png" width="140" height="95" /></a>
	<a target="_blank" href="show_img.php?url=image/Leaf_senscence_phenotype_database.png"><img border="0" src="image/Leaf_senscence_phenotype_database.png" width="140" height="95" /></a>
</div>

<p class="sltext" style="font-size:16px; line-height:23px; text-indent:2em;">
<br/><br/>
<B><font size="-1">Please Cite:</font></B><br/>
<font size="-1">
Li, Z., Zhao, Y., Liu, X., Peng, J., Guo, H., and Luo, J. (2013). LSD 2.0: an update of the leaf senescence database. Nucleic Acids Res. 42(D1): D1200-D1205. <a href="http://nar.oxfordjournals.org/content/42/D1/D1200" target="_blank"><b>[Full Text]</b></a><br/><br/>
Liu, X., Li, Z., Jiang, Z., Zhao, Y., Peng, J., Jin, J., Guo, H., and Luo, J. (2011). LSD: a leaf senescence database. Nucleic Acids Res. 39: D1103-1107. <a href="http://nar.oxfordjournals.org/content/39/suppl_1/D1103" target="_blank"><b>[Full Text]</b></a><br/>
</font><br/>
<br/>
</p>
</div>
</body>
</html>
