1546920023­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/­index
1546926315­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/advanced_search.php­Advanced Search
1546927932­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/­index
1546928884­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypesearchgene.php­Phenotypesearchgene
1546930943­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546931238­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_gene_detail.php­Get Gene Detail
1546931667­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_qtl_info.php­Get Qtl Info
1546932046­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_qtl_info.php­Get Qtl Info
1546933490­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546935045­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546936667­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546937714­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546937913­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546937997­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546938527­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546938542­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546949744­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/getseqtoweblab.php­Getseqtoweblab
1546956616­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browse_species.php­Browse Species
1547001620­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/getseqtoweblab.php­Getseqtoweblab
