1546924757­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browse_species.php­Browse Species
1546924802­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546926677­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546928278­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/­index
1546928298­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546928408­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546931687­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_qtl_info.php­Get Qtl Info
1546932002­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/links.php­Links
1546932024­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/feedback.php­Feedback
1546932317­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/­index
1546932326­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546932332­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546932454­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_ath_mutant_seed.php­Get Ath Mutant Seed
1546932460­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_qtl_info.php­Get Qtl Info
1546933251­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546933252­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546934199­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546935126­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134­unknown­/get_qtl_info.php­Get Qtl Info
1546935129­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134­unknown­/get_qtl_info.php­Get Qtl Info
1546935136­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134­unknown­/about.php­About
1546935138­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134­unknown­/links.php­Links
1546935139­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134­unknown­/feedback.php­Feedback
1546937908­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546938000­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypesearchmutant.php­Phenotypesearchmutant
1546938045­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546941832­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546944693­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546945900­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546949851­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/getseqtoweblab.php­Getseqtoweblab
1546950974­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/getseqtoweblab.php­Getseqtoweblab
