1546924773­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_gene_detail.php­Get Gene Detail
1546928043­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/­index
1546928117­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/­index
1546928121­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546928413­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_gene_detail.php­Get Gene Detail
1546928881­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_mutant_detail.php­Get Mutant Detail
1546929501­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546929507­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546930989­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546931214­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browse_mutant.php­Browse Mutant
1546931293­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/search_gene_result.php­Search Gene Result
1546932012­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/submit.php­Submit
1546932040­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/blast.php­Blast
1546932061­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/­index
1546934204­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546935053­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_qtl_info.php­Get Qtl Info
1546937713­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546938361­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546942342­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/blast.php­Blast
1546942361­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/blast.php­Blast
1546944731­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546944797­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546947057­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546949607­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/getseqtoweblab.php­Getseqtoweblab
1546956620­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/getseqtoweblab.php­Getseqtoweblab
