1546921151­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546921213­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/­index
1546921346­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_gene_detail.php­Get Gene Detail
1546921354­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546926680­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546928127­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546928287­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_qtl_info.php­Get Qtl Info
1546928499­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546928501­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browse_species.php­Browse Species
1546928510­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_gene_seq.php­Get Gene Seq
1546929503­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546931216­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546931257­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/search_primer_result.php­Search Primer Result
1546931298­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/advanced_search.php­Advanced Search
1546931647­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546931707­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/search_pubmed_result.php­Search Pubmed Result
1546932323­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546935128­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546935130­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546935132­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546938016­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546938491­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546938601­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546942924­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/­index
1546943730­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546944288­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/getseqtoweblab.php­Getseqtoweblab
1546944695­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546945678­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/getseqtoweblab.php­Getseqtoweblab
1546948786­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/getseqtoweblab.php­Getseqtoweblab
1547002697­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/getseqtoweblab.php­Getseqtoweblab
