1546919911­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/­index
1546921333­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_table.php­Browsespecies By Table
1546926335­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_qtl_info.php­Get Qtl Info
1546928872­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypesearchgene.php­Phenotypesearchgene
1546929605­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546930587­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browsespecies_by_tree.php­Browsespecies By Tree
1546931268­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/advanced_search.php­Advanced Search
1546931282­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/advanced_search.php­Advanced Search
1546931371­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/blast.php­Blast
1546931420­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/get_qtl_info.php­Get Qtl Info
1546932043­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/advanced_search.php­Advanced Search
1546933257­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546935133­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134­unknown­/browse_mutant.php­Browse Mutant
1546935138­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134­unknown­/submit.php­Submit
1546935820­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546937911­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/phenotypeBrowse.php­PhenotypeBrowse
1546943059­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/­index
1546943567­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/browse_species.php­Browse Species
1546944813­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/getseqtoweblab.php­Getseqtoweblab
1546948521­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/getseqtoweblab.php­Getseqtoweblab
1547002014­unknown­::1­unknown­Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36­unknown­/getseqtoweblab.php­Getseqtoweblab
